name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    env: # ✅ Injection des variables d'environnement dès le job
      NEXT_PUBLIC_FORMSPREE_ID: ${{ vars.NEXT_PUBLIC_FORMSPREE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        run: |
          # Install dependencies including optional dependencies
          npm ci --include=optional
          # Rebuild native dependencies for the current platform
          npm rebuild
          
      - name: Setup environment
        run: |
          echo "NEXT_PUBLIC_FORMSPREE_ID=$NEXT_PUBLIC_FORMSPREE_ID" > .env.production
          echo "NODE_ENV=production" >> .env.production
          # Ensure the .next/cache directory exists
          mkdir -p .next/cache

      - name: Build with Next.js
        env:
          NEXT_PUBLIC_FORMSPREE_ID: ${{ vars.NEXT_PUBLIC_FORMSPREE_ID }}
          # Optimize build performance
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          # Clean previous builds
          rm -rf .next
          # Build the application
          npm run build
          # Export to static files
          npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out/
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
